CODABLE(TestCodable)
FIELD(uint8_t, a)
FIELD(uint16_t, b)
DEFAULT_FIELD(uint32_t, c, 7)
FIELD(uint64_t, d)
FIELD(int8_t, e)
FIELD(int16_t, f)
DEFAULT_FIELD(int32_t, g, 8)
FIELD(int64_t, h)
STRING(10, s)
FIELD(float32_t, f1)
FIELD(float64_t, f2)
PADDING(3)
PADDING(3)
STRING(10, s2)
CONST_STRING(cs, "match")
